default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: hello_rails

test:
  <<: *default
  database: hello_rails_test

production:
  <<: *default
  database: your_app_name_production
  username: your_production_postgres_username
  password: your_production_postgres_password
